version: '3'
services:
  nuxt:
    build: .
    command: yarn run dev
    working_dir: /nuxt
    volumes:
      - ./nuxt:/nuxt:delegated
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
      - "9229:9229"